contact_links:
  - name: Предложение
    url: https://discord.station13.ru
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.station13.ru
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности Morty#7384 в Discord.
